package br.com.trixo.cms.entity.publicacao;

public enum CausaErro {

    INDETERMINADO, CONECTAR_HOST, LOGAR_HOST, CRIAR_PASTAS_PADROES, GERAR_ARQUIVO_PUBLICACAO, GERAR_PAGINA, ENVIAR_PAGINA, MOVER_PAGINA, EXCLUIR_PASTAS_TEMPORARIAS, ESCREVER_LOG;

}
